[main]
num_threads = 12
dt_pde = 0.020000
simulation_time = 5000.0
abort_on_no_activity = false
use_adaptivity = 0

[ode_solver]
dt = 0.020000
use_gpu = 0
gpu_id = 0
library_file = shared_libs/libminimal_model.so

[stim_1_11]
main_function = stim_x_y_z_limits
start = 4001
duration = 2
current = 0.5
min_x = 10213.7
max_x = 12213.7
min_y = 5993.88
max_y = 7993.88
min_z = 15419.8
max_z = 17419.8

[stim_2_11]
main_function = stim_x_y_z_limits
start = 4001
duration = 2.0
current = 0.5
min_x = 11216.2
max_x = 13216.2
min_y = 4855.41
max_y = 6855.41
min_z = 11714.5
max_z = 13714.5

[stim_3_11]
main_function = stim_x_y_z_limits
start = 4001
duration = 2.0
current = 0.5
min_x = 13668.3
max_x = 15668.3
min_y = 5489.08
max_y = 7489.08
min_z = 7171.87
max_z = 9171.87

[stim_4_11]
main_function = stim_x_y_z_limits
start = 4016
duration = 2.0
current = 0.5
min_x = 15419.8
max_x = 17419.8
min_y = 9506.4
max_y = 11506.4
min_z = 7300.97
max_z = 9300.97

[stim_1_12]
main_function = stim_x_y_z_limits
start = 4351
duration = 2
current = 0.5
min_x = 10213.7
max_x = 12213.7
min_y = 5993.88
max_y = 7993.88
min_z = 15419.8
max_z = 17419.8

[stim_2_12]
main_function = stim_x_y_z_limits
start = 4351
duration = 2.0
current = 0.5
min_x = 11216.2
max_x = 13216.2
min_y = 4855.41
max_y = 6855.41
min_z = 11714.5
max_z = 13714.5

[stim_3_12]
main_function = stim_x_y_z_limits
start = 4351
duration = 2.0
current = 0.5
min_x = 13668.3
max_x = 15668.3
min_y = 5489.08
max_y = 7489.08
min_z = 7171.87
max_z = 9171.87

[stim_4_12]
main_function = stim_x_y_z_limits
start = 4366
duration = 2.0
current = 0.5
min_x = 15419.8
max_x = 17419.8
min_y = 9506.4
max_y = 11506.4
min_z = 7300.97
max_z = 9300.97

[domain]
main_function = initialize_grid_with_hu_mesh_with_scar
name = Coelho Salinet
original_discretization = 500.0
desired_discretization = 500.0
num_volumes = 11771
mesh_file = meshes/coelho.alg
num_extra_fields = 11
start_dx = 500.000000
start_dy = 500.000000
start_dz = 500.000000

[assembly_matrix]
main_function = anisotropic_sigma_assembly_matrix_for_rabbit_mesh
init_function = set_initial_conditions_fvm
library_file = ./shared_libs/libdefault_matrix_assembly.so
sigma_factor = 0.0
sigma_l = 0.000158625
sigma_t = 0.000196393
sigma_n = 0.000285348
sigma_endo_dense = 0.000210222
fibers_in_mesh = true
number_layers_bz = 0

[update_monodomain]
main_function = update_monodomain_default

[linear_system_solver]
main_function = conjugate_gradient
init_function = init_conjugate_gradient
end_function = end_conjugate_gradient
library_file = ./shared_libs/libdefault_linear_system_solver.so
tolerance = 1e-9
use_preconditioner = no
use_gpu = no
max_iterations = 200

[extra_data]
main_function = set_extra_data_for_scv_mesh
library_file = ./shared_libs/libdefault_extra_data.so

[save_result]
main_function = save_with_activation_times
init_function = init_save_with_activation_times
end_function = end_save_with_activation_times
library_file = ./shared_libs/libdefault_save_mesh.so
print_rate = 100
output_dir = ./outputs/coelho_inferencia_simulation_v2/
binary = true
mesh_format = ensight
mesh_print_rate = 100
file_prefix = V
last_stimulus_time = 5112.0
vm_threshold = -86.0
time_threshold=0.0
activation_threshold=0.3
apd_threshold=0.2
remove_older_simulations=1

;[save_state]
;main_function = save_simulation_state_with_activation_times
;library_file = ./shared_libs/libdefault_save_state.so
;output_dir = ./outputs/coelho_apresentacao_10stims/

[restore_state]
main_function=restore_simulation_state
input_dir=./outputs/coelho_inferencia_v2/

[calc_ecg]
main_function = pseudo_bidomain
init_function = init_pseudo_bidomain
end_function = end_pseudo_bidomain
library_file = ./shared_libs/libdefault_calc_ecg.so
calc_rate = 10
lead1 = -27032.4,59885.8,-25899.2
lead2 = -38496.1,59833.5,-5957.17
lead3 = -32547.6,42361.2,-15847.9
lead4 = -26597.1,24888.8,-25740.6
lead5 = -38060.8,24836.6,-5798.62
lead6 = -25962.9,-26100.7,-25509.6
lead7 = -37426.6,-26153,-5567.61
lead8 = -31478,-43634.3,-15458.3
lead9 = -25527.4,-61106.6,-25351
lead10 = -36991.1,-61158.9,-5409.01
sigma_b = 20
use_gpu = false
filename = ./outputs/coelho_inferencia_simulation/ecg.txt

